# 4.Решите пожалуйста следующие задачи. Каждую задачу лучше выполнять вотдельном блоке Code в Colab.



a.Импортируйте библиотеку NumPy

In [1]:
import numpy as np

b.Создайте массив из 10 нулей

In [2]:
array=np.zeros(10)
print("Массив из 10 нулей:")
print(array)

Массив из 10 нулей:
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


c.Создать массив из 10 единиц

In [3]:
array=np.ones(10)
print("Массив из 10 единиц:")
print(array)

Массив из 10 единиц:
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


d.Создать массив из 10 пятерок

In [4]:
array=np.ones(10)*5
print("Массив из 10 пятерок:")
print(array)

Массив из 10 пятерок:
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


e.Создать массив из целых чисел от 10 до 50

In [5]:
array=np.arange(10,51)
print("Массив из целых чисел от 10 до 50:")
print(array)

Массив из целых чисел от 10 до 50:
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]


f.Создать массив из четных чисел от 10 до 50

In [6]:
array=np.arange(10,51,2)
print("Массив из четных чисел от 10 до 50:")
print(array)

Массив из четных чисел от 10 до 50:
[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]


g.Создать матрицу 3х3 с числами от 0 до 8

In [7]:
m1 = np.arange(9).reshape(3,3) 
print (m1)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


h.Создать единичную матрицу 3x3

In [8]:
m2 = np.ones(9).reshape(3,3) 
print(m2)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


i.Используйте NumPy для генерации случайного числа от 0 до 1

In [9]:
np.random.rand()

0.7326597428096523

j.Используйте NumPy для генерации массива из 25 случайных чисел,взятых из стандартного нормального распределения

In [10]:
np.random.normal(size=25)

array([ 0.71419336,  0.72313659,  1.10472431,  0.97296773, -0.19189515,
       -0.12730615, -0.11112204,  0.64591806,  0.41364352,  0.61370676,
       -0.61668216, -0.75634015, -1.90577398,  0.50851943,  0.77564181,
        0.64087342,  0.32795503, -0.17627771,  0.08487805,  0.88559412,
        1.31790887, -0.3169259 , -1.06310258,  0.26977802,  2.06690027])

k.Создайте следующую матрицу используя функции библиотеки NumPy:

In [11]:
mat1 = np.arange(1,101).reshape(10,10)
print(mat1/100)


[[0.01 0.02 0.03 0.04 0.05 0.06 0.07 0.08 0.09 0.1 ]
 [0.11 0.12 0.13 0.14 0.15 0.16 0.17 0.18 0.19 0.2 ]
 [0.21 0.22 0.23 0.24 0.25 0.26 0.27 0.28 0.29 0.3 ]
 [0.31 0.32 0.33 0.34 0.35 0.36 0.37 0.38 0.39 0.4 ]
 [0.41 0.42 0.43 0.44 0.45 0.46 0.47 0.48 0.49 0.5 ]
 [0.51 0.52 0.53 0.54 0.55 0.56 0.57 0.58 0.59 0.6 ]
 [0.61 0.62 0.63 0.64 0.65 0.66 0.67 0.68 0.69 0.7 ]
 [0.71 0.72 0.73 0.74 0.75 0.76 0.77 0.78 0.79 0.8 ]
 [0.81 0.82 0.83 0.84 0.85 0.86 0.87 0.88 0.89 0.9 ]
 [0.91 0.92 0.93 0.94 0.95 0.96 0.97 0.98 0.99 1.  ]]


l.Дана стартовая матрица (обязательно запустите код ниже в вашемрешении!). Эта матрица будет использоваться в последующих задачах

`это наша стартовая матрица`

In [12]:
mat2 = np.arange(1,26).reshape(5,5)
print(mat2)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


Необходимо написать код который вернет следующую матрицу из стартовой:

In [13]:
mat2 = np.arange(1,26).reshape(5,5)
print(mat2[2:, :-1]+1)

[[12 13 14 15]
 [17 18 19 20]
 [22 23 24 25]]


m.Написать код обращения к элементу который вернет значение  20 изстартовой матрицы задачи l

In [14]:
mat2 = np.arange(1,26).reshape(5,5)
print(mat2[3,4])

20


n.Написать код к стартовой матрице задачи l , который воспроизводитвывод, показанный ниже

In [15]:
mat2 = np.arange(1,26).reshape(5,5)
result = mat2[0:3,[1]]
print(result)

[[ 2]
 [ 7]
 [12]]


o.Написать код к стартовой матрице задачи l , который воспроизводитвывод, показанный ниже

In [16]:
mat2 = np.arange(1,26).reshape(5,5)
print(mat2[-1:])

[[21 22 23 24 25]]


p.Написать код к стартовой матрице задачи l , который воспроизводитвывод, показанный ниже

In [17]:
mat2 = np.arange(1,26).reshape(5,5)
print(mat2[-2:])

[[16 17 18 19 20]
 [21 22 23 24 25]]


q.Получить сумму всех значений в стартовой матрице mat

In [18]:
mat2 = np.arange(1,26).reshape(5,5)
sum_all = mat2.sum()
print('Сумма всех значений:')
print(sum_all)

Сумма всех значений:
325


r.Получить стандартное отклонение в стартовой матрице mat

In [19]:
mat2 = np.arange(1,26).reshape(5,5)
np.std(mat2)

7.211102550927978

s.Получить сумму значений в колонках в стартовой матрице mat

In [20]:
mat2 = np.arange(1,26).reshape(5,5)
mat2.sum(axis=0)

array([55, 60, 65, 70, 75])